import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../app/globals.css'
import { ReactNode } from 'react'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import AuthSession from './_component/AuthSession'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'write-now',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions);

  return (
    <html>
      <body>
        <AuthSession>
              {children}
        </AuthSession>
      </body>
    </html>
  )
}
